server:
  port: ${PORT:18471}
spring:
  application:
    name: Legal contract digitizer
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
ethereum:
  rpc:
    url: ${ETH_RPC_URL:https://sepolia.infura.io/v3/${INFURA_PROJECT_ID}}
  walletKeystore:
    password: "${ETH_WALLET_KEYSTORE_PASSWORD}"
  chain:
    id: ${ETH_CHAIN_ID:11155111}  # Defaults to Sepolia testnet chain id
  etherscan:
    url: ${ETH_ETHERSCAN_URL:https://sepolia.etherscan.io}
google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI:https://legal-contract-digitizer.firebaseapp.com/__/auth/handler}