server:
  port: ${PORT:18471}
spring:
  application:
    name: Legal contract digitizer
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
ethereum:
  rpc:
    url: ${ETH_RPC_URL:https://sepolia.infura.io/v3/${INFURA_PROJECT_ID}}
  private:
    key: "${ETH_PRIVATE_KEY}"
  chain:
    id: ${ETH_CHAIN_ID:11155111}  # Defaults to Sepolia testnet chain id